/**
 * Removes recorded legacy lesson data (monthly_student_records, then monthly_lessons) and nothing else:
 * organizations, users, classes, subjects, teachers, students, assignments and monthly
 * records are left untouched.
 *
 * Usage:
 *   npx tsx scripts/clear-recorded-data.ts              clear the database at DATABASE_URL
 *   npx tsx scripts/clear-recorded-data.ts --dry-run    report what would be deleted
 *   npx tsx scripts/clear-recorded-data.ts --sql        print SQL for the remote D1 database
 *
 * The remote D1 database has no binding in a plain tsx process, so deployment cleanup runs:
 *   npx tsx scripts/clear-recorded-data.ts --sql > clear-recorded-data.sql
 *   npx wrangler d1 execute student-academic-reporting-db --remote --file clear-recorded-data.sql
 */
import { db } from '../src/db';
import { lessons, records } from '../src/db/schema';
import { count } from 'drizzle-orm';

const SQL_STATEMENTS = [
  '-- Generated by scripts/clear-recorded-data.ts',
  '-- Run with: npx wrangler d1 execute student-academic-reporting-db --remote --file clear-recorded-data.sql',
  'DELETE FROM monthly_student_records;',
  'DELETE FROM monthly_lessons;',
];

const args = process.argv.slice(2);
const dryRun = args.includes('--dry-run');
const sqlMode = args.includes('--sql');
const unknown = args.filter((a) => a !== '--dry-run' && a !== '--sql');

async function rowCounts() {
  const [lessonCount] = await db.select({ n: count() }).from(lessons);
  const [recordCount] = await db.select({ n: count() }).from(records);
  return { lessons: Number(lessonCount?.n || 0), records: Number(recordCount?.n || 0) };
}

async function main() {
  if (unknown.length) throw new Error(`Unknown option(s): ${unknown.join(' ')}. Use --dry-run or --sql.`);

  if (sqlMode) {
    console.log(SQL_STATEMENTS.join('\n'));
    return;
  }

  const before = await rowCounts();
  if (dryRun) {
    console.log(`Dry run: would delete ${before.records} legacy student records and ${before.lessons} legacy lesson reports. Nothing was changed.`);
    return;
  }

  await db.delete(records);
  await db.delete(lessons);

  const after = await rowCounts();
  console.log(`Deleted ${before.records - after.records} legacy student records and ${before.lessons - after.lessons} legacy lesson reports.`);
  console.log(`Remaining: ${after.lessons} legacy lesson reports, ${after.records} legacy student records.`);
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
